{
 "title": "Upgrade Responder",
 "description": "The dashboard for the Upgrade Responder project",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "AppName", "query": "${VAR_APPNAME}" }
  ]
 },
 "panels": [
  {
   "title": "$AppName Public Metrics Dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "The metrics we're showing here are collected using ${AppName} Upgrade Responder Service, which will notify the user when a new release of ${AppName} is available.\n\nThe source code is available at https://github.com/longhorn/upgrade-responder ."
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Node Map",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "$tag_country_isocode",
     "groupBy": [
      { "params": [ "country_isocode" ], "type": "tag" }
     ],
     "measurement": "by_country_code_down_sampling",
     "query": "SELECT last(\"total\") FROM \"by_country_code_down_sampling\" WHERE $timeFilter GROUP BY \"country_isocode\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Node Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upgrade_request_down_sampling",
     "query": "SELECT last(\"total\") FROM \"upgrade_request_down_sampling\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Node By $AppName Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_app_version",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "app_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "by_app_version_down_sampling",
     "query": "SELECT last(\"total\") FROM \"by_app_version_down_sampling\" WHERE $timeFilter GROUP BY time(1h), \"app_version\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}